# Generated by Django 2.1.1 on 2018-12-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('IsAgree', models.CharField(db_column='IsAgree', max_length=5)),
                ('BookingStatus', models.CharField(db_column='BookingStatus', default='Pending', max_length=100)),
                ('DepositAmount', models.DecimalField(db_column='DepositAmount', decimal_places=8, max_digits=10)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'db_table': 'Booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingPaySlip',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('BankAccountName', models.CharField(db_column='BankAccountName', max_length=255)),
                ('AccountNo', models.CharField(db_column='AccountNo', max_length=255)),
                ('BranchName', models.CharField(db_column='BranchName', max_length=255)),
                ('PaySlipDoc', models.CharField(db_column='PaySlipDoc', max_length=255)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'db_table': 'BookingPaySlip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('IsDelivered', models.CharField(db_column='IsDelivered', default='N', max_length=100)),
                ('DeliveryDate', models.DateTimeField(auto_now_add=True, db_column='DeliveryDate')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
                ('EditDate', models.DateTimeField(auto_now_add=True, db_column='EditDate')),
            ],
            options={
                'db_table': 'DeliveryPoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepositBankInfo',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('BankAccountName', models.CharField(db_column='BankAccountName', max_length=255)),
                ('AccountNo', models.CharField(db_column='AccountNo', max_length=255)),
                ('BranchName', models.CharField(db_column='BranchName', max_length=255)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'db_table': 'DepositBankInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('Id', models.AutoField(db_column='DistrictID', primary_key=True, serialize=False)),
                ('DistrictCode', models.CharField(db_column='DistrictCode', max_length=50)),
                ('DistrictName', models.CharField(db_column='DistrictName', max_length=100)),
                ('DivisionId', models.IntegerField(db_column='DivisionID')),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'db_table': 'Inbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InboxDetail',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Message', models.CharField(db_column='Message', max_length=255)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'db_table': 'InboxDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('ProductName', models.CharField(db_column='ProductName', max_length=50)),
                ('ProductColor', models.CharField(db_column='ProductColor', max_length=50)),
                ('ProductPrice', models.DecimalField(db_column='ProductPrice', decimal_places=8, max_digits=10)),
                ('MinBookingPrice', models.DecimalField(db_column='MinBookingPrice', decimal_places=8, max_digits=10)),
                ('Stock', models.IntegerField(db_column='Stock')),
                ('ProductImage1', models.CharField(db_column='ProductImage1', max_length=255)),
                ('ProductImage2', models.CharField(db_column='ProductImage2', max_length=255)),
                ('ProductImage3', models.CharField(db_column='ProductImage3', max_length=255)),
                ('EditDate', models.DateTimeField(auto_now_add=True, db_column='EditDate')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductBookingPeriod',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Period', models.IntegerField(db_column='Period')),
                ('EditDate', models.DateTimeField(auto_now_add=True, db_column='EditDate')),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'db_table': 'ProductBookingPeriod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('UserName', models.CharField(db_column='UserName', max_length=255)),
                ('Mobile', models.CharField(db_column='Mobile', max_length=255)),
                ('Email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('IsUsed', models.CharField(db_column='IsUsed', default='N', max_length=10)),
                ('Status', models.CharField(db_column='Status', default='1', max_length=10)),
                ('Remark', models.CharField(db_column='Remark', default='1', max_length=10)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'db_table': 'RegisteredUser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YamahaUser',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('UserId', models.CharField(db_column='UserId', max_length=255)),
                ('UserName', models.CharField(db_column='UserName', max_length=255)),
                ('Password', models.CharField(db_column='Password', max_length=255)),
                ('IsAdmin', models.CharField(db_column='IsAdmin', default='0', max_length=10)),
                ('Status', models.CharField(db_column='Status', default='Y', max_length=10)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'db_table': 'YamahaUser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('OtpCode', models.CharField(db_column='OtpCode', max_length=255)),
                ('Email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('IsUsed', models.CharField(db_column='IsUsed', default='N', max_length=10)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'db_table': 'SMSText',
            },
        ),
    ]
